/*
 * Wavefront REST API
 * <p>The Wavefront REST API enables you to interact with Wavefront servers using standard REST API tools. You can use the REST API to automate commonly executed operations such as automatically tagging sources.</p><p>When you make REST API calls outside the Wavefront REST API documentation you must add the header \"Authorization: Bearer &lt;&lt;API-TOKEN&gt;&gt;\" to your HTTP requests.</p>
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wavefront.rest.models;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Timeseries
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-25T16:34:08.557+05:30")
public class Timeseries {
  @SerializedName("label")
  private String label = null;

  @SerializedName("host")
  private String host = null;

  @SerializedName("tags")
  private Map<String, String> tags = null;

  @SerializedName("data")
  private List<List<Float>> data = null;

  public Timeseries label(String label) {
    this.label = label;
    return this;
  }

  /**
   * Label of this timeseries
   *
   * @return label
   **/
  @ApiModelProperty(value = "Label of this timeseries")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Timeseries host(String host) {
    this.host = host;
    return this;
  }

  /**
   * Source/Host of this timeseries
   *
   * @return host
   **/
  @ApiModelProperty(value = "Source/Host of this timeseries")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public Timeseries tags(Map<String, String> tags) {
    this.tags = tags;
    return this;
  }

  public Timeseries putTagsItem(String key, String tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<String, String>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

  /**
   * Tags (key-value annotations) of this timeseries
   *
   * @return tags
   **/
  @ApiModelProperty(value = "Tags (key-value annotations) of this timeseries")
  public Map<String, String> getTags() {
    return tags;
  }

  public void setTags(Map<String, String> tags) {
    this.tags = tags;
  }

  public Timeseries data(List<List<Float>> data) {
    this.data = data;
    return this;
  }

  public Timeseries addDataItem(List<Float> dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<List<Float>>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Data returned by this time series.  This is returned as a list of points, where each point is represented as a two-element list with 1st element being the timestamp in epoch SECONDS and the 2nd element being the numeric value of the series at the timestamp
   *
   * @return data
   **/
  @ApiModelProperty(value = "Data returned by this time series.  This is returned as a list of points, where each point is represented as a two-element list with 1st element being the timestamp in epoch SECONDS and the 2nd element being the numeric value of the series at the timestamp")
  public List<List<Float>> getData() {
    return data;
  }

  public void setData(List<List<Float>> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Timeseries timeseries = (Timeseries) o;
    return Objects.equals(this.label, timeseries.label) &&
        Objects.equals(this.host, timeseries.host) &&
        Objects.equals(this.tags, timeseries.tags) &&
        Objects.equals(this.data, timeseries.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, host, tags, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Timeseries {\n");

    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

